[tool.poetry]
name = "personal-ai-assistant"
version = "0.1.0"
description = ""
authors = ["gczarny <grzegorz.czarny93@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
